### PR TITLE
add the same build script as the old bexp

### PR DESCRIPTION
**Pull request by DerTiedemann**

### CODE REVIEW

**Comment by DerTiedemann** [comment]
@Ayagoumi is this also broken on master?

**Comment by Ayagoumi** [comment]
@DerTiedemann  I believe so, yes.

**Comment by DerTiedemann** [comment]
@Ayagoumi the ci treats [warnings as errors](https://github.com/chain4travel/react-camino-block-explorer/runs/7247320340?check_suite_focus=true#step:5:1), i could turn that off but would say that this PR builds and is live here:
https://playground.explorer.camino.foundation/

**Comment by Ayagoumi** [comment]
@DerTiedemann Looks good now.

**Review by Ayagoumi — APPROVED** [review]

**Pull request merged**
